### ISSUE TITLE
ES state storage retry logic / survive loss of cluster

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#989]
Stage storage in the worker and execution controller needs to better handle ES failure scenarios with the goal of being able to completely turn off the state cluster without having a job fail. 

Upon the return of the state cluster or successful retry of the state update the job should resume where it left off with no operator intervention required.

There should be no coordination between the workers and execution controller required in these scenarios. They should manage this independently but we need to be cognizant of the risk of having a worker incorrectly detecting this failure and appearing to get stuck.

Obviously clear logging of the workers state will be required.

**Comment by peterdemartini** [comment]
Is this fixed now?

**Comment by kstaken** [comment]
I think we can close this now. If we still have issues they should get new more specific tickets.
